///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace StreamlineRegressionTests.Actions.SettingsPageLibrary
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ClickSettings recording.
    /// </summary>
    [TestModule("876199dc-1924-4771-afa4-744ae6063988", ModuleType.Recording, 1)]
    public partial class ClickSettings : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::StreamlineRegressionTests.StreamlineRegressionTestsRepository repository.
        /// </summary>
        public static global::StreamlineRegressionTests.StreamlineRegressionTestsRepository repo = global::StreamlineRegressionTests.StreamlineRegressionTestsRepository.Instance;

        static ClickSettings instance = new ClickSettings();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ClickSettings()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ClickSettings Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmMain.BtnSettings' at 173;52.", repo.FrmMain.BtnSettingsInfo, new RecordItemIndex(0));
            repo.FrmMain.BtnSettings.Click("173;52");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'FrmMain.TabControlPanel2'.", repo.FrmMain.TabControlPanel2Info, new RecordItemIndex(1));
            Validate.Exists(repo.FrmMain.TabControlPanel2Info);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='SETTINGS') on item 'FrmMain.LblHeader'.", repo.FrmMain.LblHeaderInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.FrmMain.LblHeaderInfo, "Text", "SETTINGS");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
