///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace StreamlineRegressionTests.Actions.PartPage
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The deletePart recording.
    /// </summary>
    [TestModule("5b32e479-056a-4958-86b6-392164372c5b", ModuleType.Recording, 1)]
    public partial class deletePart : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::StreamlineRegressionTests.StreamlineRegressionTestsRepository repository.
        /// </summary>
        public static global::StreamlineRegressionTests.StreamlineRegressionTestsRepository repo = global::StreamlineRegressionTests.StreamlineRegressionTestsRepository.Instance;

        static deletePart instance = new deletePart();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public deletePart()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static deletePart Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmMain.Sdfsd' at 128;16.", repo.FrmMain.SdfsdInfo, new RecordItemIndex(0));
            repo.FrmMain.Sdfsd.Click("128;16");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmMain.ElementBtnDelete' at 41;45.", repo.FrmMain.ElementBtnDeleteInfo, new RecordItemIndex(1));
            repo.FrmMain.ElementBtnDelete.Click("41;45");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmMain.Btn4' at 96;47.", repo.FrmMain.Btn4Info, new RecordItemIndex(2));
            repo.FrmMain.Btn4.Click("96;47");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
