///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace StreamlineRegressionTests
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the StreamlineRegressionTestsRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("ecee2a7b-122e-45cf-9998-e81a0d31589e")]
    public partial class StreamlineRegressionTestsRepository : RepoGenBaseFolder
    {
        static StreamlineRegressionTestsRepository instance = new StreamlineRegressionTestsRepository();
        StreamlineRegressionTestsRepositoryFolders.FrmMainAppFolder _frmmain;

        /// <summary>
        /// Gets the singleton class instance representing the StreamlineRegressionTestsRepository element repository.
        /// </summary>
        [RepositoryFolder("ecee2a7b-122e-45cf-9998-e81a0d31589e")]
        public static StreamlineRegressionTestsRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public StreamlineRegressionTestsRepository() 
            : base("StreamlineRegressionTestsRepository", "/", null, 0, false, "ecee2a7b-122e-45cf-9998-e81a0d31589e", ".\\RepositoryImages\\StreamlineRegressionTestsRepositoryecee2a7b.rximgres")
        {
            _frmmain = new StreamlineRegressionTestsRepositoryFolders.FrmMainAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("ecee2a7b-122e-45cf-9998-e81a0d31589e")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The FrmMain folder.
        /// </summary>
        [RepositoryFolder("44089ce2-7c94-41b3-9f1d-de539dc5d2ff")]
        public virtual StreamlineRegressionTestsRepositoryFolders.FrmMainAppFolder FrmMain
        {
            get { return _frmmain; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class StreamlineRegressionTestsRepositoryFolders
    {
        /// <summary>
        /// The FrmMainAppFolder folder.
        /// </summary>
        [RepositoryFolder("44089ce2-7c94-41b3-9f1d-de539dc5d2ff")]
        public partial class FrmMainAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btn4Info;
            RepoItemInfo _lblheaderInfo;
            RepoItemInfo _btnsettingsInfo;
            RepoItemInfo _tabcontrolpanel2Info;
            RepoItemInfo _btnbackInfo;
            RepoItemInfo _gradgroupbox2Info;

            /// <summary>
            /// Creates a new FrmMain  folder.
            /// </summary>
            public FrmMainAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FrmMain", "/form[@automationid='FrmMain']", parentFolder, 30000, null, true, "44089ce2-7c94-41b3-9f1d-de539dc5d2ff", "")
            {
                _btn4Info = new RepoItemInfo(this, "Btn4", "container[@automationid='DlgMessageBox']/?/?/element[@automationid='Btn4']", ".//element[@automationid='Btn4']", 30000, null, "1e323cc1-67a2-4031-9ba7-e8e18a91e374");
                _lblheaderInfo = new RepoItemInfo(this, "LblHeader", "?/?/text[@automationid='LblHeader']", "?/?/text[@automationid='LblHeader']", 30000, null, "aedde176-316e-4863-8680-29103f9566ce");
                _btnsettingsInfo = new RepoItemInfo(this, "BtnSettings", "container[@automationid='start']/?/?/element[@automationid='BtnSettings']", ".//element[@automationid='BtnSettings']", 30000, null, "402c16fc-2db5-4ef5-a73b-9363101f3e39");
                _tabcontrolpanel2Info = new RepoItemInfo(this, "TabControlPanel2", "container[@automationid='settings']/?/?/container[@automationid='tabControlPanel2']", ".//container[@automationid='tabControlPanel2']", 30000, null, "edafc40f-e4b6-4fa2-9da5-96b030611363");
                _btnbackInfo = new RepoItemInfo(this, "BtnBack", "?/?/element[@automationid='BtnBack']", "?/?/element[@automationid='BtnBack']", 30000, null, "47845dff-f31f-444a-8b20-083d2b374ca3");
                _gradgroupbox2Info = new RepoItemInfo(this, "GradGroupBox2", "?/?/container[@automationid='gradGroupBox2']", "?/?/container[@automationid='gradGroupBox2']", 30000, null, "8e4e54b9-9462-4227-85bb-f4ee3d4ede1f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("44089ce2-7c94-41b3-9f1d-de539dc5d2ff")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("44089ce2-7c94-41b3-9f1d-de539dc5d2ff")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Btn4 item.
            /// </summary>
            [RepositoryItem("1e323cc1-67a2-4031-9ba7-e8e18a91e374")]
            public virtual Ranorex.Unknown Btn4
            {
                get
                {
                    return _btn4Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Btn4 item info.
            /// </summary>
            [RepositoryItemInfo("1e323cc1-67a2-4031-9ba7-e8e18a91e374")]
            public virtual RepoItemInfo Btn4Info
            {
                get
                {
                    return _btn4Info;
                }
            }

            /// <summary>
            /// The LblHeader item.
            /// </summary>
            [RepositoryItem("aedde176-316e-4863-8680-29103f9566ce")]
            public virtual Ranorex.Text LblHeader
            {
                get
                {
                    return _lblheaderInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LblHeader item info.
            /// </summary>
            [RepositoryItemInfo("aedde176-316e-4863-8680-29103f9566ce")]
            public virtual RepoItemInfo LblHeaderInfo
            {
                get
                {
                    return _lblheaderInfo;
                }
            }

            /// <summary>
            /// The BtnSettings item.
            /// </summary>
            [RepositoryItem("402c16fc-2db5-4ef5-a73b-9363101f3e39")]
            public virtual Ranorex.Unknown BtnSettings
            {
                get
                {
                    return _btnsettingsInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The BtnSettings item info.
            /// </summary>
            [RepositoryItemInfo("402c16fc-2db5-4ef5-a73b-9363101f3e39")]
            public virtual RepoItemInfo BtnSettingsInfo
            {
                get
                {
                    return _btnsettingsInfo;
                }
            }

            /// <summary>
            /// The TabControlPanel2 item.
            /// </summary>
            [RepositoryItem("edafc40f-e4b6-4fa2-9da5-96b030611363")]
            public virtual Ranorex.Container TabControlPanel2
            {
                get
                {
                    return _tabcontrolpanel2Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The TabControlPanel2 item info.
            /// </summary>
            [RepositoryItemInfo("edafc40f-e4b6-4fa2-9da5-96b030611363")]
            public virtual RepoItemInfo TabControlPanel2Info
            {
                get
                {
                    return _tabcontrolpanel2Info;
                }
            }

            /// <summary>
            /// The BtnBack item.
            /// </summary>
            [RepositoryItem("47845dff-f31f-444a-8b20-083d2b374ca3")]
            public virtual Ranorex.Unknown BtnBack
            {
                get
                {
                    return _btnbackInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The BtnBack item info.
            /// </summary>
            [RepositoryItemInfo("47845dff-f31f-444a-8b20-083d2b374ca3")]
            public virtual RepoItemInfo BtnBackInfo
            {
                get
                {
                    return _btnbackInfo;
                }
            }

            /// <summary>
            /// The GradGroupBox2 item.
            /// </summary>
            [RepositoryItem("8e4e54b9-9462-4227-85bb-f4ee3d4ede1f")]
            public virtual Ranorex.Container GradGroupBox2
            {
                get
                {
                    return _gradgroupbox2Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The GradGroupBox2 item info.
            /// </summary>
            [RepositoryItemInfo("8e4e54b9-9462-4227-85bb-f4ee3d4ede1f")]
            public virtual RepoItemInfo GradGroupBox2Info
            {
                get
                {
                    return _gradgroupbox2Info;
                }
            }
        }

    }
#pragma warning restore 0436
}
